Repository binbashar/leverage, pull requests merged in 2023-04, with the labels that each got.

#183 [126] Kubectl: remove unnecessary shenanigans for MFA
  leverage/_utils.py
  leverage/container.py
  leverage/containers/kubectl.py
  tests/test_containers/test_kubectl.py
Labels: fix, patch

#185 Fixed order to get last tag
  .github/workflows/build-push-package.yml
Labels: fix, patch

#186 Fix/build workflow tag sort fixed
  .github/workflows/build-push-package.yml
Labels: fix, patch

#194 [192] Code format & style w/ Black
  .github/workflows/black.yaml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  build.py
  conftest.py
  leverage/__init__.py
  leverage/_internals.py
  leverage/_parsing.py
  leverage/_utils.py
  leverage/conf.py
  leverage/container.py
  leverage/leverage.py
  leverage/logger.py
  leverage/modules/aws.py
  leverage/modules/credentials.py
  leverage/modules/project.py
  leverage/modules/run.py
  leverage/modules/terraform.py
  leverage/modules/tfautomv.py
  leverage/path.py
  leverage/tasks.py
  pyproject.toml
  tests/bats/leverage.bats
  tests/build_scripts/load_env_build.py
  tests/build_scripts/simple_build.py
  tests/conftest.py
  tests/test__parsing.py
  tests/test_conf.py
  tests/test_containers/test_kubectl.py
  tests/test_logger.py
  tests/test_modules/test_run.py
  tests/test_path.py
  tests/test_tasks.py
Labels: enhancement, patch

#188 [36] Automatically enter code when aws sso login
  leverage/_utils.py
  leverage/container.py
  leverage/logger.py
  leverage/modules/aws.py
  tests/conftest.py
  tests/test_containers/__init__.py
  tests/test_containers/test_aws.py
  tests/test_containers/test_kubectl.py
  tests/test_containers/test_terraform.py
Labels: feature, patch

#198 renaming github workflows files and the actions names in order to be …
  .github/workflows/release-management-github.yml
  .github/workflows/release-pypi-build-push-package.yml
  .github/workflows/release-pypi-build-push-test-package.yml
  .github/workflows/test-lint-black.yaml
  .github/workflows/tests-unit-and-integration.yml
Labels: enhancement, patch
