Repository binbashar/leverage, pull requests merged in 2023-01, with the labels that each got.

#151 Issue 123 all layers option
  .github/workflows/run-tests.yml
  Makefile
  leverage/container.py
  leverage/modules/aws.py
  leverage/modules/terraform.py
Labels: minor, feature

#149 Issue 141 s3 key multi region support
  .github/workflows/build-push-test-package.yml
  .github/workflows/run-tests.yml
  Makefile
  README.md
  leverage/__init__.py
  leverage/container.py
  leverage/leverage.py
  leverage/modules/__init__.py
  leverage/modules/aws.py
  leverage/modules/credentials.py
  leverage/modules/terraform.py
  leverage/modules/tfautomv.py
Labels: enhancement, minor

#155 Set python version in setup-python action
  .github/workflows/build-push-package.yml
Labels: bug, patch

#154 ISSUE-153 added Dod-CCP reference to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, patch

#150 [Snyk] Security upgrade wheel from 0.37.1 to 0.38.0
  dev-requirements.txt
Labels: enhancement, patch

#164 ISSUE-163 Removed s3-key-by-parameter on init
  .github/workflows/run-tests.yml
  leverage/modules/terraform.py
Labels: bug, patch
