Repository binbashar/leverage, pull requests merged in 2024-09, with the labels that each got.

#274 [159] Fix issue with argument parsing logic for tf apply
  leverage/logger.py
  leverage/modules/terraform.py
  tests/test_modules/terraform/__init__.py
  tests/test_modules/terraform/test_handle_apply_arguments_parsing.py
  tests/test_modules/test_terraform.py
Labels: fix, patch

#280 feat: Add python 3.12 to test workflows
  .github/workflows/tests-integration.yaml
  .github/workflows/tests-unit.yml
  tests/test_containers/test_kubectl.py
  tests/test_containers/test_terraform.py
  tests/test_modules/test_credentials.py
Labels: patch

#284 feat: Increase compatibiliy with podman
  leverage/container.py
Labels: minor

#285 feat: Increase account dir search depth
  leverage/path.py
  tests/test_path.py
Labels: minor
