Repository binbashar/leverage, pull requests merged in 2024-04, with the labels that each got.

#249 [BB-248] Improving test coverage
  .github/workflows/tests-integration.yaml
  .github/workflows/tests-unit.yml
  leverage/modules/credentials.py
  leverage/modules/tfautomv.py
  tests/test_modules/test_credentials.py
Labels: enhancement, patch

#250 [BB-235] project short name validation
  leverage/modules/project.py
  tests/test_modules/test_project.py
Labels: enhancement, patch

#256 [229] Fix issue with --version option
  leverage/modules/credentials.py
  leverage/modules/project.py
  leverage/path.py
  tests/test_path.py
  tests/test_root_path.py
Labels: bug, patch

#260 [159] Improve apply arguments parsing logic
  .github/workflows/tests-integration.yaml
  leverage/modules/terraform.py
  tests/test_modules/terraform/__init__.py
  tests/test_modules/terraform/test_handle_apply_arguments_parsing.py
Labels: bug, patch

#261 [157] Refactor of build processes and dependency management using Poetry
  .coveragerc
  .github/workflows/release-pypi-build-push-package.yml
  .github/workflows/release-pypi-build-push-test-package.yml
  .github/workflows/tests-integration.yaml
  .github/workflows/tests-unit.yml
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  dev-requirements.txt
  entrypoint.sh
  poetry.lock
  pyproject.toml
  setup.cfg
  setup.py
  tests/bats/utils.bash
Labels: documentation, enhancement, patch
